-- MySQL Script generated by MySQL Workbench
-- Fri Sep  3 11:30:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercise_looper
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exercise_looper` ;

-- -----------------------------------------------------
-- Schema exercise_looper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise_looper` DEFAULT CHARACTER SET utf8 ;
USE `exercise_looper` ;

-- -----------------------------------------------------
-- Table `exercise_looper`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise_looper`.`exercises` ;

CREATE TABLE IF NOT EXISTS `exercise_looper`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_looper`.`takes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise_looper`.`takes` ;

CREATE TABLE IF NOT EXISTS `exercise_looper`.`takes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_stamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_looper`.`fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise_looper`.`fields` ;

CREATE TABLE IF NOT EXISTS `exercise_looper`.`fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  `value_kind` INT NOT NULL,
  `exercises_id` INT NOT NULL,
  PRIMARY KEY (`id`, `exercises_id`),
  INDEX `fk_fields_exercises1_idx` (`exercises_id` ASC) VISIBLE,
  CONSTRAINT `fk_fields_exercises1`
    FOREIGN KEY (`exercises_id`)
    REFERENCES `exercise_looper`.`exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_looper`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exercise_looper`.`answers` ;

CREATE TABLE IF NOT EXISTS `exercise_looper`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `response` TEXT NOT NULL,
  `fields_id` INT NOT NULL,
  `takes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fields_id`, `takes_id`),
  INDEX `fk_answers_fields1_idx` (`fields_id` ASC) VISIBLE,
  INDEX `fk_answers_takes1_idx` (`takes_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_fields1`
    FOREIGN KEY (`fields_id`)
    REFERENCES `exercise_looper`.`fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answers_takes1`
    FOREIGN KEY (`takes_id`)
    REFERENCES `exercise_looper`.`takes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
